FROM node:20-alpine AS build
WORKDIR /app
COPY Web/package*.json ./
RUN npm install
COPY Web/ ./
RUN npm run build

FROM nginx:mainline-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY Docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
